### ISSUE TITLE
img file

### ISSUE THREAD

**Issue by harsh9190** [crazo7924/twrp_device_realme_rmx3241#1]
can i get img file for it?

**Comment by crazo7924** [comment]
I've not compiled yet. Need some free time for that.

**Comment by harsh9190** [comment]
CAN YOU PLEASE DO IT FOR ME? I AM HAVING SOME TRUBLE.... PLEASE

**Comment by crazo7924** [comment]
> CAN YOU PLEASE DO IT FOR ME? I AM HAVING SOME TRUBLE.... PLEASE

Have you unlocked the bootloader?

**Comment by harsh9190** [comment]
YES
